import { NextResponse } from "next/server";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/auth";
import type { MoodKey } from "@/lib/spotify";

export const dynamic = "force-dynamic";

const allowedMoods: MoodKey[] = [
  "happy",
  "sad",
  "angry",
  "surprised",
  "neutral",
];

export async function POST(request: Request) {
  const session = await getServerSession(authOptions);

  if (!session?.accessToken) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const body = await request.json().catch(() => ({}));
  const trackUris = Array.isArray(body.tracks) ? body.tracks : [];
  const moodParam = body.mood ?? "neutral";
  const mood = allowedMoods.includes(moodParam as MoodKey)
    ? (moodParam as MoodKey)
    : "neutral";

  if (trackUris.length === 0) {
    return NextResponse.json(
      { error: "No tracks provided" },
      { status: 400 }
    );
  }

  const profileResponse = await fetch("https://api.spotify.com/v1/me", {
    headers: { Authorization: `Bearer ${session.accessToken}` },
    cache: "no-store",
  });

  if (!profileResponse.ok) {
    const errorText = await profileResponse.text().catch(() => "");
    let errorMessage = "Failed to read profile";
    let errorPayload: unknown = undefined;

    try {
      errorPayload = JSON.parse(errorText);
      errorMessage = (errorPayload as any)?.error?.message ?? errorMessage;
    } catch {
      // Response was not JSON.
    }

    return NextResponse.json(
      {
        error: errorMessage,
        status: profileResponse.status,
        statusText: profileResponse.statusText,
        details: errorText,
        spotifyError: errorPayload,
      },
      { status: profileResponse.status }
    );
  }

  const profile = await profileResponse.json();

  const playlistResponse = await fetch(
    `https://api.spotify.com/v1/me/playlists`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${session.accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: body.name ?? `Moodinator ${mood} mix`,
        description: "Generated by MOODINATOR",
        public: false,
      }),
    }
  );

  if (!playlistResponse.ok) {
    const errorText = await playlistResponse.text().catch(() => "");
    let errorMessage = "Failed to create playlist";
    let errorPayload: unknown = undefined;

    try {
      errorPayload = JSON.parse(errorText);
      errorMessage = (errorPayload as any)?.error?.message ?? errorMessage;
    } catch {
      // Response was not JSON.
    }

    return NextResponse.json(
      {
        error: errorMessage,
        status: playlistResponse.status,
        statusText: playlistResponse.statusText,
        details: errorText,
        spotifyError: errorPayload,
      },
      { status: playlistResponse.status }
    );
  }

  const playlist = await playlistResponse.json();

  const addTracksResponse = await fetch(
    `https://api.spotify.com/v1/playlists/${playlist.id}/tracks`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${session.accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ uris: trackUris }),
    }
  );

  if (!addTracksResponse.ok) {
    const errorText = await addTracksResponse.text().catch(() => "");
    let errorMessage = "Failed to add tracks";
    let errorPayload: unknown = undefined;

    try {
      errorPayload = JSON.parse(errorText);
      errorMessage = (errorPayload as any)?.error?.message ?? errorMessage;
    } catch {
      // Response was not JSON.
    }

    return NextResponse.json(
      {
        error: errorMessage,
        status: addTracksResponse.status,
        statusText: addTracksResponse.statusText,
        details: errorText,
        spotifyError: errorPayload,
      },
      { status: addTracksResponse.status }
    );
  }

  return NextResponse.json({
    id: playlist.id,
    url: playlist.external_urls?.spotify,
  });
}
