import { NextResponse } from "next/server";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/auth";
import type { MoodKey } from "@/lib/spotify";

export const dynamic = "force-dynamic";

const allowedMoods: MoodKey[] = [
  "happy",
  "sad",
  "angry",
  "surprised",
  "neutral",
];

type SpotifyPlaylist = {
  id: string;
  name?: string;
  external_urls?: { spotify?: string };
};

type SpotifyPlaylistPage = {
  items?: SpotifyPlaylist[];
  next?: string | null;
};

async function findExistingPlaylist(
  accessToken: string,
  targetName: string
): Promise<SpotifyPlaylist | null> {
  let nextUrl: string | null = "https://api.spotify.com/v1/me/playlists?limit=50";

  while (nextUrl) {
    const response: Response = await fetch(nextUrl, {
      headers: { Authorization: `Bearer ${accessToken}` },
      cache: "no-store",
    });

    if (!response.ok) {
      const errorText = await response.text().catch(() => "");
      let errorPayload: unknown = undefined;

      try {
        errorPayload = JSON.parse(errorText);
      } catch {
        // Response was not JSON.
      }

      throw new Error(
        (errorPayload as any)?.error?.message ??
          `Failed to list playlists (${response.status})`
      );
    }

    const data = (await response.json()) as SpotifyPlaylistPage;
    const items = Array.isArray(data?.items) ? data.items : [];
    const match = items.find(
      (playlist) => playlist?.name?.toLowerCase() === targetName.toLowerCase()
    );

    if (match) {
      return match;
    }

    nextUrl = data?.next ?? null;
  }

  return null;
}

export async function POST(request: Request) {
  const session = await getServerSession(authOptions);

  if (!session?.accessToken) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const body = await request.json().catch(() => ({}));
  const trackUris = Array.isArray(body.tracks) ? body.tracks : [];
  const moodParam = body.mood ?? "neutral";
  const mood = allowedMoods.includes(moodParam as MoodKey)
    ? (moodParam as MoodKey)
    : "neutral";

  if (trackUris.length === 0) {
    return NextResponse.json(
      { error: "No tracks provided" },
      { status: 400 }
    );
  }

  const profileResponse = await fetch("https://api.spotify.com/v1/me", {
    headers: { Authorization: `Bearer ${session.accessToken}` },
    cache: "no-store",
  });

  if (!profileResponse.ok) {
    const errorText = await profileResponse.text().catch(() => "");
    let errorMessage = "Failed to read profile";
    let errorPayload: unknown = undefined;

    try {
      errorPayload = JSON.parse(errorText);
      errorMessage = (errorPayload as any)?.error?.message ?? errorMessage;
    } catch {
      // Response was not JSON.
    }

    return NextResponse.json(
      {
        error: errorMessage,
        status: profileResponse.status,
        statusText: profileResponse.statusText,
        details: errorText,
        spotifyError: errorPayload,
      },
      { status: profileResponse.status }
    );
  }

  await profileResponse.json();
  const playlistName = body.name ?? `Moodinator ${mood} mix`;
  let playlist = null;

  try {
    playlist = await findExistingPlaylist(session.accessToken, playlistName);
  } catch (error) {
    return NextResponse.json(
      {
        error:
          error instanceof Error ? error.message : "Failed to list playlists",
      },
      { status: 500 }
    );
  }

  if (!playlist) {
    const playlistResponse = await fetch(
      `https://api.spotify.com/v1/me/playlists`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${session.accessToken}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          name: playlistName,
          description: "Generated by MOODINATOR",
          public: false,
        }),
      }
    );

    if (!playlistResponse.ok) {
      const errorText = await playlistResponse.text().catch(() => "");
      let errorMessage = "Failed to create playlist";
      let errorPayload: unknown = undefined;

      try {
        errorPayload = JSON.parse(errorText);
        errorMessage = (errorPayload as any)?.error?.message ?? errorMessage;
      } catch {
        // Response was not JSON.
      }

      return NextResponse.json(
        {
          error: errorMessage,
          status: playlistResponse.status,
          statusText: playlistResponse.statusText,
          details: errorText,
          spotifyError: errorPayload,
        },
        { status: playlistResponse.status }
      );
    }

    playlist = await playlistResponse.json();
  }

  const replaceTracksResponse = await fetch(
    `https://api.spotify.com/v1/playlists/${playlist.id}/tracks`,
    {
      method: "PUT",
      headers: {
        Authorization: `Bearer ${session.accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ uris: trackUris }),
    }
  );

  if (!replaceTracksResponse.ok) {
    const errorText = await replaceTracksResponse.text().catch(() => "");
    let errorMessage = "Failed to replace tracks";
    let errorPayload: unknown = undefined;

    try {
      errorPayload = JSON.parse(errorText);
      errorMessage = (errorPayload as any)?.error?.message ?? errorMessage;
    } catch {
      // Response was not JSON.
    }

    return NextResponse.json(
      {
        error: errorMessage,
        status: replaceTracksResponse.status,
        statusText: replaceTracksResponse.statusText,
        details: errorText,
        spotifyError: errorPayload,
      },
      { status: replaceTracksResponse.status }
    );
  }

  return NextResponse.json({
    id: playlist.id,
    url: playlist.external_urls?.spotify,
  });
}
